from __future__ import annotations

from pathlib import Path


PACKAGE_DIR = Path(__file__).resolve().parents[1]
REPO_DIR = PACKAGE_DIR.parent

DEFAULT_DATA_DIR = PACKAGE_DIR / "data"
DEFAULT_IMAGES_DIR = PACKAGE_DIR / "images"
DEFAULT_OUTPUT_DIR = PACKAGE_DIR / "outputs"
DEFAULT_PRODUCTS_DIR = DEFAULT_OUTPUT_DIR / "products"
DEFAULT_PERSONAS_DIR = DEFAULT_OUTPUT_DIR / "personas"
DEFAULT_QUERY_PLAN_DIR = DEFAULT_OUTPUT_DIR / "query_plan"
DEFAULT_RESPONSES_DIR = DEFAULT_OUTPUT_DIR / "responses"
DEFAULT_EMBEDDINGS_DIR = DEFAULT_OUTPUT_DIR / "embeddings"

PRICE_SCALE = 590.0
DEFAULT_TOP_N_PRODUCTS = 100
DEFAULT_MAX_PERSONAS = 50
DEFAULT_EXPOSURE_N = 200
DEFAULT_MAX_DEMAND_SUPPORT = 400
